---
# tasks file for ansible-role-wireshark

- name: install package
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ wireshark_package }}"

- name: create wireshark group
  group:
    name: wireshark
    state: present

- name: add current user to wireshark group
  user:
    name: "{{ wireshark_user }}"
    append: yes
    groups: wireshark
