---
# tasks file for ansible-role-wireshark

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# # Setup/install tasks.
# - include: setup-RedHat.yml
#   when: ansible_distribution == 'CentOS' or ansible_distribution =='RedHat'
#
# - include: setup-Fedora.yml
#   when: ansible_distribution == 'Fedora'
#
# - include: setup-Debian.yml
#   when: ansible_os_family == 'Debian'

- name: install cli package
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ wireshark_cli_package }}"
  when: wireshark_cli

- name: install gui package
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ wireshark_cli_package }}"
  when: wireshark_gui

- name: create wireshark group
  group:
    name: wireshark
    state: present

- name: add current user to wireshark group
  user:
    name: "{{ wireshark_user }}"
    append: yes
    groups: wireshark
