---
# tasks file for ansible-role-wireshark

- name: install cli package
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ wireshark_cli_package }}"
  when: wireshark_cli

- name: install gui package
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ wireshark_cli_package }}"
  when: wireshark_gui

- name: create wireshark group
  group:
    name: wireshark
    state: present

- name: add current user to wireshark group
  user:
    name: "{{ wireshark_user }}"
    append: yes
    groups: wireshark

when: ansible_distribution == 'CentOS' and ansible_distribution_version == '6.4'

when: ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise'

when: ansible_distribution == 'Debian' and ansible_distribution_version == '7'

when: ansible_os_family == "RedHat" and ansible_lsb.major_release|int >= 5
